spring.application.name=orquestrador-service

# define a porta exclusiva do orquestrador
server.port=8083

# credenciais e endereço do RabbitMQ (padronizado com os outros serviços)
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# configuracoes do banco de dados h2 em memoria
spring.datasource.url=jdbc:h2:mem:orquestradordb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ativa o hibernate para criar a tabela TransacaoSaga automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# habilita a interface web do banco (acessivel via http://localhost:8083/h2-console)
spring.h2.console.enabled=true