spring.application.name=orquestrador-service

server.port=8083

# credenciais e endereço do RabbitMQ (padronizado com os outros serviços)
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# configuracoes do banco de dados h2 em memoria
spring.datasource.url=jdbc:h2:mem:orquestradordb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# habilita a interface web do banco
spring.h2.console.enabled=true