spring.application.name=custodia-service

server.port=8082

# o custódia precisa plugar no mesmo rabbitmq para ouvir a fila
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# configurações do banco de dados h2 em memória para a custódia
spring.datasource.url=jdbc:h2:mem:custodiadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# habilita o console do h2 na porta 8082
spring.h2.console.enabled=true